config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :datos
  resources :cells
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
end

app/models/dato.rb
class Dato < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  before_action :set_cell, only: [:show, :edit, :update, :destroy]

  # GET /cells
  # GET /cells.json
  def index
    @cells = Cell.all
  end

  # GET /cells/1
  # GET /cells/1.json
  def show
  end

  # GET /cells/new
  def new
    @cell = Cell.new
  end

  # GET /cells/1/edit
  def edit
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(cell_params)

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Cell was successfully created.' }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1
  # PATCH/PUT /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to @cell, notice: 'Cell was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell.destroy
    respond_to do |format|
      format.html { redirect_to cells_url, notice: 'Cell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
      @cell = Cell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_params
      params.require(:cell).permit(:phone, :brnd, :description, :color, :price)
    end
end

app/controllers/datos_controller.rb
class DatosController < ApplicationController
  before_action :set_dato, only: [:show, :edit, :update, :destroy]

  # GET /datos
  # GET /datos.json
  def index
    @datos = Dato.all
  end

  # GET /datos/1
  # GET /datos/1.json
  def show
  end

  # GET /datos/new
  def new
    @dato = Dato.new
  end

  # GET /datos/1/edit
  def edit
  end

  # POST /datos
  # POST /datos.json
  def create
    @dato = Dato.new(dato_params)

    respond_to do |format|
      if @dato.save
        format.html { redirect_to @dato, notice: 'Dato was successfully created.' }
        format.json { render :show, status: :created, location: @dato }
      else
        format.html { render :new }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos/1
  # PATCH/PUT /datos/1.json
  def update
    respond_to do |format|
      if @dato.update(dato_params)
        format.html { redirect_to @dato, notice: 'Dato was successfully updated.' }
        format.json { render :show, status: :ok, location: @dato }
      else
        format.html { render :edit }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos/1
  # DELETE /datos/1.json
  def destroy
    @dato.destroy
    respond_to do |format|
      format.html { redirect_to datos_url, notice: 'Dato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dato
      @dato = Dato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dato_params
      params.require(:dato).permit(:nombres, :apellidos, :rol, :cargo, :fechanacimiento)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombres, :apellidos, :rol, :cargo, :fechanacimiento)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/datos_helper.rb
module DatosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/cells/_form.html.erb
<%= form_for(cell) do |f| %>
  <% if cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :brnd %>
    <%= f.text_field :brnd %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cells/edit.html.erb
<h1>Editing Cell</h1>

<%= render 'form', cell: @cell %>

<%= link_to 'Show', @cell %> |
<%= link_to 'Back', cells_path %>

app/views/cells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cells</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Brnd</th>
      <th>Description</th>
      <th>Color</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cells.each do |cell| %>
      <tr>
        <td><%= cell.phone %></td>
        <td><%= cell.brnd %></td>
        <td><%= cell.description %></td>
        <td><%= cell.color %></td>
        <td><%= cell.price %></td>
        <td><%= link_to 'Show', cell %></td>
        <td><%= link_to 'Edit', edit_cell_path(cell) %></td>
        <td><%= link_to 'Destroy', cell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cell', new_cell_path %>

app/views/cells/new.html.erb
<h1>New Cell</h1>

<%= render 'form', cell: @cell %>

<%= link_to 'Back', cells_path %>

app/views/cells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @cell.phone %>
</p>

<p>
  <strong>Brnd:</strong>
  <%= @cell.brnd %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cell.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cell.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cell.price %>
</p>

<%= link_to 'Edit', edit_cell_path(@cell) %> |
<%= link_to 'Back', cells_path %>

app/views/datos/_form.html.erb
<%= form_for(dato) do |f| %>
  <% if dato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dato.errors.count, "error") %> prohibited this dato from being saved:</h2>

      <ul>
      <% dato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %>
    <%= f.text_field :nombres %>
  </div>

  <div class="field">
    <%= f.label :apellidos %>
    <%= f.text_field :apellidos %>
  </div>

  <div class="field">
    <%= f.label :rol %>
    <%= f.text_area :rol %>
  </div>

  <div class="field">
    <%= f.label :cargo %>
    <%= f.text_area :cargo %>
  </div>

  <div class="field">
    <%= f.label :fechanacimiento %>
    <%= f.datetime_select :fechanacimiento %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datos/edit.html.erb
<h1>Editing Dato</h1>

<%= render 'form', dato: @dato %>

<%= link_to 'Show', @dato %> |
<%= link_to 'Back', datos_path %>

app/views/datos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Datos</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Rol</th>
      <th>Cargo</th>
      <th>Fechanacimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datos.each do |dato| %>
      <tr>
        <td><%= dato.nombres %></td>
        <td><%= dato.apellidos %></td>
        <td><%= dato.rol %></td>
        <td><%= dato.cargo %></td>
        <td><%= dato.fechanacimiento %></td>
        <td><%= link_to 'Show', dato %></td>
        <td><%= link_to 'Edit', edit_dato_path(dato) %></td>
        <td><%= link_to 'Destroy', dato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dato', new_dato_path %>

app/views/datos/new.html.erb
<h1>New Dato</h1>

<%= render 'form', dato: @dato %>

<%= link_to 'Back', datos_path %>

app/views/datos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @dato.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @dato.apellidos %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @dato.rol %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @dato.cargo %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @dato.fechanacimiento %>
</p>

<%= link_to 'Edit', edit_dato_path(@dato) %> |
<%= link_to 'Back', datos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenAlcivar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for(usuario) do |f| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %>
    <%= f.text_field :nombres %>
  </div>

  <div class="field">
    <%= f.label :apellidos %>
    <%= f.text_field :apellidos %>
  </div>

  <div class="field">
    <%= f.label :rol %>
    <%= f.text_area :rol %>
  </div>

  <div class="field">
    <%= f.label :cargo %>
    <%= f.text_area :cargo %>
  </div>

  <div class="field">
    <%= f.label :fechanacimiento %>
    <%= f.datetime_select :fechanacimiento %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Rol</th>
      <th>Cargo</th>
      <th>Fechanacimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombres %></td>
        <td><%= usuario.apellidos %></td>
        <td><%= usuario.rol %></td>
        <td><%= usuario.cargo %></td>
        <td><%= usuario.fechanacimiento %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @usuario.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @usuario.rol %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @usuario.cargo %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @usuario.fechanacimiento %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>